### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by djcedr** [tanaikech/UnzipGs#3]
Hi, for some reason I get an error while trying to use UnzipGs. The fileId is correct and I'm not using v8 with this...
Any idea please?
Thanks!
Cédric

Error	
InternalError: Cannot convert Array to (class)[].,Exception: Could not unzip.
(anonymous)	@ Code.gs:63
unzip	@ Code.gs:18
sample	@ Code.gs:6

**Comment by djcedr** [comment]
@tanaikech, tagging you just to make sure you get a notification - thanks!

**Comment by tanaikech** [comment]
Thank you for your comment. Unfortunately, from your comment, I cannot replicate your situation. This is due to my poor skill. I deeply apologize for this. By the way, I think that from your error message, this might be due to the library of "unzip.min.js". How about this?

Unfortunately, I cannot still replicate your issue. I apologize for my poor skill. In order to correctly understand about your situation, can you provide the detail flow and your whole script? By this, I would like to confirm it.

**Comment by tanaikech** [comment]
Unfortunately, I cannot still replicate your issue. I apologize for my poor skill. In order to correctly understand about your situation, can you provide the detail flow and your whole script? By this, I would like to confirm it.

**Comment by tanaikech** [comment]
Sorry. I accidentally closed it.

**Comment by djcedr** [comment]
Hello and thank you very much for your message,
I have written a small Python script and running it locally works, so I
won't be using this google app script at this time.
For reference, as asked, I am pasting below the google app script I had
tried
Thanks again and all the best

**Comment by djcedr** [comment]
```
function sample() {
  var id = "1waF7qoTO_OBt2r4q4oEMJOKRi0CccYik"; // File ID of Zip file.
  var pass = "password"; // Password.

  var blob = DriveApp.getFileById(id).getBlob();
  var res = UnzipGs.unzip(blob, { password: pass }); // or UnzipGs.unzip(blob);
  res.forEach(function(e) {
    Logger.log(
      "filename: %s, mimeType: %s, size: %s",
      e.getName(),
      e.getContentType(),
      e.getBytes().length
    );
  });
}

```

**Comment by tanaikech** [comment]
Thank you for replying. Unfortunately, I cannot replicate your situation. I deeply apologize for this.

By the way, as I have already said, this library uses "[unzip.min.js](https://github.com/imaya/zlib.js/blob/develop/bin/unzip.min.js)". So I thought that your issue might be due to "[unzip.min.js](https://github.com/imaya/zlib.js/blob/develop/bin/unzip.min.js)". Because the error occurs at https://github.com/tanaikech/UnzipGs/blob/master/UnzipGs.js#L63 How do you think about it? If my understanding is correct, I think that this might depend on the ZIP data. In this case, I cannot resolve your issue. I apologize for this.

**Comment by djcedr** [comment]
I share your analysis. As I said I have found another way to solve my need,
so i won't investigate further on unzip.min.js, but thank you again for
your reply and all the best

**Comment by tanaikech** [comment]
Thank you for replying. I deeply apologize that I couldn't be useful. This is due to my poor skill. I would like to study more and more.

**Comment by ghost** [comment]
Hi. Sorry for my bad English.
I guess `toGas` occur the InternalError.
You know, range of Blob[] values is -128 to 127.
So when taking 128 expect -128, but this code computes 128 to 128.
And, `Utilities.newBlob([128])` will crash.

```diff
    toGas = function(ar_) {
      var a;
      a = ar_.map(function(e) {
        var res;
-        res = e > 128 ? e - 256 : e;
+        res = e >= 128 ? e - 256 : e;
        return res;
      });
      return Utilities.newBlob(a);
    };
```

**Comment by tanaikech** [comment]
@takumab21 Thank you for your comment. I could confirm it. Now, I fixed it and updated to v1.0.1. Could you please confirm it? https://github.com/tanaikech/UnzipGs#update-history

**Comment by ghost** [comment]
@tanaikech
Thank you for your quick response.
I ran djcedr's sample code with my ZIP file which has problem same as first comment by v1.0.1 (v2 on GAS), seems to work good.

**Comment by tanaikech** [comment]
@takumab21 Thank you for testing it. The issue was able to be resolved by your support. Thank you so much.
